name: Test Go
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.17.0"
      - name: Go dependencies
        uses: go mod tidy
      - name: Run Test
        uses: GOTEST=test go test -v ./test